### PR TITLE
fix, log error

### PR DESCRIPTION
**Pull request by prugel**
1. 'success' is global variable.
    So if one package is fail then others will not display although success.

2. display grouping success/fail

### CODE REVIEW

**Comment by mzgol** [comment]
Hi @prugel. I don't understand the problem, could you provide a specific example? Also, any changes need to pass the unit tests. Changing the output format would surely break a lot of them so I'm not sure I want to change that unless there is a very important reason.

In non-verbose mode all you get are error & log arrays, you can log it in whichever way you want.

**Comment by prugel** [comment]
// bower.json
  "dependencies": {
    "iCheck": "~1.0.2",
    "ngDialog": "~0.4.0",
    "ngpager": "~1.1.0",
    "slimScroll": "~1.3.6",
    "sweetalert": "~1.1.0",
    "angular": "~1.4.3"
  }

if  ngpager and angular is fail. then it will be display

expected
```
iCheck: installed: 1.0.2, expected: ~1.0.2
ngDialog: installed: 0.4.0, expected: ~0.4.0
ngpager: installed: 0.9.0, expected: ~1.1.0     // fail
slimScroll: installed: 1.3.6, expected: ~1.3.6
sweetalert: installed: 1.1.0, expected: ~1.1.0
angular: installed: 1.4.3, expected: ~1.4.3      // fail
```

but 
```
iCheck: installed: 1.0.2, expected: ~1.0.2
ngDialog: installed: 0.4.0, expected: ~0.4.0
ngpager: installed: 0.9.0, expected: ~1.1.0     // fail
angular: installed: 1.4.3, expected: ~1.4.3      // fail
```

slimScroll, sweetalert message do not display

**Comment by mzgol** [comment]
Thanks, I understand now. I'd prefer to separate any styling changes and actual bug fixes. Could you just fix the bug (I assume one `if (success)` check was wrong when logging) and add a test to [test/spec.js](https://github.com/mzgol/check-dependencies/blob/master/test/spec.js) and remove other changes from the PR?

Note that there already is an `output` object, no need to duplicate it in `logs`.

**Comment by prugel** [comment]
Sorry, I don't know how to remove other changes.

**Comment by mzgol** [comment]
You can just modify the code back to the way it was, add a new commit with the changes and push to the same branch. GitHub will pick it up automatically, no need to create a new PR.

**Pull request closed without merging**
